name: Weather Data Automation

on:
  schedule:
    - cron: '0 10 * * *' # Run daily at 10am UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make weather.sh Executable
      run: chmod +x weather.sh

    - name: Run Weather Script
      run: ./weather.sh

    - name: Commit and Push Changes
      run: |
        git config --global user.name "corpuschris"
        git config --global user.email "netofr@gmail.com"
        git add data/weather/
        git commit -m "Automated update of weather data"
        git push
